server:
  port: 8080

# 数据库配置
spring:
  datasource:
    # MySQL 配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13579
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

  # MongoDB 配置
  data:
    mongodb:
      uri: mongodb+srv://cluster0.kxiwgw4.mongodb.net/springboot
      host: cluster0.kxiwgw4.mongodb.net
      port: 27017
      database: test
      username: witherr
      password: witherr
      authentication-database: admin

# 配置mybatis实体和xml映射(mybatis plus)
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.via.entity






